server:
  port: 3344
spring:
  application:
    name: microservice-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/memory140662/microservice-cloud-config.git