server:
  port: 8001
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                 # 數據庫連接池的最小維持連接數
      initial-size: 5                             # 初始化連接數
      max-total: 5                                # 最大連接數
      max-wait-millis: 200                        # 等待連接獲取的最大超時時間
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/

info:
  app.name: microservicecloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01Test
  profiles: test