eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway-9527.com

info:
  app.name: microservicecloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$

server:
  port: 9527


spring:
  application:
    name: microservice-cloud-zuul-gateway

zuul:
  routes:
    dept.serviceId: microservicecloud-dept
    dept.path: /my-dept/**
#  ignored-services: microservicecloud-dept
  ignored-services: "*"
  prefix: /leo
